### ISSUE TITLE
DRO Relative/feeback

### ISSUE THREAD

**Issue by alkabal** [rubienr/bbb-linuxcnc-config#3]
It is possible to map macro button or remap some existing button (like M-home Safe-Z W-home) for choose to display Machine coordinates vs Work coordinates ?

Thanks, best regards

**Comment by alkabal** [comment]
Hi

I have found some flags in source code about macro5 and macro7 hardcoded for swap over Relative/Absolute mode.

I have make some change for using safe-z and swap from Relative/Absolute with only one button.

Br

**Comment by rubienr** [comment]
Sorry for the late reply: due to lack of time the development is still on hold until Nov./Dec. 18'. Will fix minor driver issues and create a pull-request and come back to your question.
