### ISSUE TITLE
Display and customizing data

### ISSUE THREAD

**Issue by alkabal** [rubienr/bbb-linuxcnc-config#4]
Hi

Did you know how to add some infor to 1st row 11 signs, i like to add toolchanger number if this is possible.

I have see someone able to display his own data but i don't understand how is possible ???

Your source code make me thinking this is  not possible but : https://forum.linuxcnc.org/10-advanced-configuration/32516-whb04b-6-manual-pulse-coder?start=10#93103

Can you says something about that ?

Thanks for sharing, Br.

**Comment by alkabal** [comment]
[log reset off on from pdnt driver 5.32](https://github.com/rubienr/bbb-linuxcnc-config/files/2409186/log.reset.off.on.from.pdnt.txt)
[log reset off on from pdnt DRIVER 3.84t](https://github.com/rubienr/bbb-linuxcnc-config/files/2409387/log.reset.off.on.from.pdnt.DRIVER.3x.txt)

Br

I can make other log for you.

**Comment by alkabal** [comment]
I have edited source code enableVerboseTx for make possible to show usb data without simulation mode
your driver send :
out   0x06fefdfe028600c8 0600000000003601 0600000100000000
0x06fefdfe status 0x02 coord1 +0134.0200 coord2 +0000.0000 coord3 +0310.0000 feed 0001 spindle rps 00000
out   0x06fefdfe028500af 0613000000003601 0600007201000000
out   size 24B hdr 0xfdfe dom 0xfe status 0x02 coord1 +0133.5039 coord2 +0000.0000 coord3 +0310.0000 feed 0370 spindle rps 00000

Mach3 driver send :
06FEFD1752455345 065420204D504720 06583A302E303030 06302020202020220 062020463A362020 06533A3020202020 0620202020000000
"06FEFD17"....RESE .T  MPG .X:0.000 .0      .  F:6  .S:0
I think something is strange with your driver but work fine i'm lost

Please can you explain a little ?

**Comment by rubienr** [comment]
Sorry for the late reply: due to lack of time the development is still on hold until Nov./Dec. 18'. Will fix minor driver issues and create a pull-request and come back to your question.

**Comment by alkabal** [comment]
Hi

No problem i wait and i'm very happy to see you again here !

Many thanks for replay i can do some logs later if you need.

**Comment by rubienr** [comment]
Hi @alkabal,

If you mean displaying custom data on the display, unfortunately this is not possible with the xhc-whb04b-6. It only accepts the following values:
* positional coordinates for each axis (x,y,z,a,b,c)
* spindle speed (rpm)
* machine state (i.e. stop/run)
* the mode (MPG, step).

Thus it is not possible to put some user defined symbols/lines/characters on the display.

hth, raoul

**Comment by rubienr** [comment]
See also this [examples](https://github.com/machinekit/machinekit/tree/master/src/hal/user_comps/xhc-whb04b-6#display-examples).
